blank_issues_enabled: false
contact_links:
  - name: PowCapServer Documentation
    url: https://github.com/izanhzh/pow-cap-server/blob/main/README.md
    about: Check the documentation before creating an issue